### ISSUE TITLE
Respond to Upgrade request using HTTP/1.1

### ISSUE THREAD

**Issue by pdonias** [xapi-project/wsproxy#24]
Using [`novnc`](https://github.com/novnc/noVNC) in the browser to connect to a VM console through `wsproxy`, I'm getting this error in Firefox (v86.0):
```
Failed when connecting: Connection closed (code: 1006)
```
But it works fine in Chrome (v88.0.4324.146).

By investigating a bit further, the only major thing I could notice is that `wsproxy` was responding to the HTTP handshake with HTTP/1.0. And if I try to proxy the connection through a local proxy that responds with HTTP/1.1, then the console works fine in Firefox.

I also experimented with a simple server that supports WebSocket upgrades (and does nothing else) and just by changing the HTTP version, Firefox is able to create a WebSocket connection or not. So even though the error message isn't very clear, I'm suspecting that Firefox doesn't allow a HTTP/1.0 response during the handshake and refuses to upgrade to the WebSocket protocol.

And I also found some instances of [people having the same issue](https://github.com/RobotWebTools/webrtc_ros/issues/40#issuecomment-633185704) with WebSocket handshakes in Firefox where the issue was the HTTP version.

The [WebSocket RFC](https://tools.ietf.org/html/rfc6455) does mention that the *client* must use HTTP/1.1:

> [The method of the request MUST be GET, and the HTTP version MUST be at least 1.1](https://tools.ietf.org/html/rfc6455#section-4.1)

It isn't as clear regarding what the server must do, but in the ["IANA Considerations"](https://tools.ietf.org/html/rfc6455#section-11.1.1) section, it says:

> Interoperability considerations
>   Use of WebSocket requires use of HTTP version 1.1 or higher.

**Comment by psafont** [comment]
I thinkthe code that manages the websocket upgrade (and returns HTTP 1.0) is https://github.com/xapi-project/xen-api-libs-transitional/blob/master/http-svr/ws_helpers.ml#L35-L53
It seems easy enough to change and test ;)

**Comment by edwintorok** [comment]
Thanks for tracking this down, we should probably check whether we need to implement anything between HTTP/1.0 and 1.1.
AFAICT:
- ensure we send a Host header
- see whether we need to do anything about persistent connections

**Comment by benjamreis** [comment]
From what I understood of [the RFC](https://tools.ietf.org/html/rfc6455), the Host head is required for the request, not for the response so I'm not sure it should be added.

**Comment by psafont** [comment]
I've tested the fix in xen-api-libs-transitional with the latest build if citrix hypervisor and it's solved now.
